import type { QuestionnaireSchema } from "./questionnaire-types";

/** Real Croatia digital nomad intake questionnaire for Sharp & Spice client portal. */
export const SHARP_SPICE_ONBOARDING_SCHEMA: QuestionnaireSchema = {
  schemaVersion: 1,
  templateKey: "croatia_digital_nomad_intake",
  title: {
    en: "Questionnaire for digital nomads in Croatia",
    ru: "Анкета для цифровых кочевников в Хорватии",
  },
  description: {
    en: "Fill all items in Latin letters (as in the passport), unless a field asks for Cyrillic. Address also in Latin.",
    ru: "Все пункты анкеты заполняются латиницей (как в загранпаспорте), если не указано иное. Адрес также заполняется латиницей.",
  },
  sections: [
    {
      id: "personal",
      order: 10,
      title: { en: "Personal data", ru: "Личные данные" },
      description: {
        en: "Identity and contact details",
        ru: "Данные о вас и контакты",
      },
      questions: [
        {
          id: "full_name_cyrillic",
          type: "text",
          order: 10,
          label: {
            en: "1. Surname, given name, patronymic (Cyrillic)",
            ru: "1. Фамилия, Имя, Отчество (кириллицей)",
          },
          placeholder: {
            en: "Ivanov Ivan Ivanovich",
            ru: "Иванов Иван Иванович",
          },
          required: true,
          layout: "full",
        },
        {
          id: "full_name_latin",
          type: "text",
          order: 20,
          label: {
            en: "2. Full name (Latin)",
            ru: "2. ФИО (латинскими)",
          },
          placeholder: { en: "IVANOV IVAN", ru: "IVANOV IVAN" },
          required: true,
          layout: "full",
          script: "latin",
        },
        {
          id: "birth_surname_latin",
          type: "text",
          order: 30,
          label: {
            en: "3. Surname at birth (Latin)",
            ru: "3. Фамилия при рождении (латинскими)",
          },
          layout: "full",
          script: "latin",
        },
        {
          id: "date_of_birth",
          type: "date",
          order: 40,
          label: { en: "4. Date of birth", ru: "4. Дата рождения" },
          placeholder: { en: "DD.MM.YYYY", ru: "DD.MM.YYYY" },
          required: true,
          layout: "half",
        },
        {
          id: "place_of_birth_latin",
          type: "text",
          order: 50,
          label: {
            en: "5. Place of birth (Latin)",
            ru: "5. Место рождения (латинскими)",
          },
          placeholder: { en: "Moscow, Russia", ru: "Moscow, Russia" },
          required: true,
          layout: "half",
          script: "latin",
        },
        {
          id: "residence_address_latin",
          type: "textarea",
          order: 60,
          label: {
            en: "6. Place of residence (address in country of citizenship, Latin)",
            ru: "6. Место жительства (адрес в стране гражданства)(латинскими)",
          },
          placeholder: {
            en: "ul. Lenina, d. 1, kv. 1, Moscow, Russia",
            ru: "ul. Lenina, d. 1, kv. 1, Moscow, Russia",
          },
          required: true,
          layout: "full",
          script: "latin",
        },
        {
          id: "phone",
          type: "phone",
          order: 70,
          label: { en: "7. Contact phone", ru: "7. Контактный телефон" },
          placeholder: { en: "+7......", ru: "+7......" },
          required: true,
          layout: "half",
        },
        {
          id: "contact_email",
          type: "email",
          order: 80,
          label: {
            en: "Email address (only .com)",
            ru: "Электронный адрес (только .com)",
          },
          placeholder: { en: "example@gmail.com", ru: "example@gmail.com" },
          required: true,
          derivedFrom: "portal_email",
          layout: "half",
        },
        {
          id: "passport_number",
          type: "text",
          order: 90,
          label: {
            en: "8. International passport number",
            ru: "8. № заграничного паспорта",
          },
          placeholder: { en: "75 1234567", ru: "75 1234567" },
          required: true,
          layout: "full",
        },
        {
          id: "passport_issued_by",
          type: "text",
          order: 100,
          label: {
            en: "Issuing authority",
            ru: "Орган выдавший документ",
          },
          placeholder: { en: "MVD 123", ru: "MVD 123" },
          layout: "half",
          script: "latin",
        },
        {
          id: "passport_issue_date",
          type: "date",
          order: 110,
          label: { en: "Date of issue", ru: "Дата выдачи" },
          required: true,
          layout: "half",
        },
        {
          id: "passport_expiry_date",
          type: "date",
          order: 120,
          label: { en: "Expiry date", ru: "Дата окончания" },
          required: true,
          layout: "half",
        },
        {
          id: "education_specialty_latin",
          type: "text",
          order: 130,
          label: {
            en: "Education / specialty (Latin)",
            ru: "Образование/специальность (латинскими)",
          },
          placeholder: {
            en: "Moscow State University",
            ru: "Moscow State University",
          },
          layout: "full",
          script: "latin",
        },
        {
          id: "citizenship_latin",
          type: "text",
          order: 140,
          label: {
            en: "10. Citizenship (Latin)",
            ru: "10. Гражданство (латинскими)",
          },
          placeholder: {
            en: "Russian Federation",
            ru: "Russian Federation",
          },
          required: true,
          layout: "half",
          script: "latin",
        },
        {
          id: "nationality_latin",
          type: "text",
          order: 150,
          label: {
            en: "11. Nationality (Latin)",
            ru: "11. Национальность (латинскими)",
          },
          placeholder: { en: "Russian", ru: "Russian" },
          required: true,
          layout: "half",
          script: "latin",
        },
        {
          id: "marital_status_latin",
          type: "text",
          order: 160,
          label: {
            en: "12. Marital status (Latin)",
            ru: "12. Семейное положение (латинскими)",
          },
          placeholder: {
            en: "Single / Married / Divorced",
            ru: "Single / Married / Divorced",
          },
          required: true,
          layout: "full",
          script: "latin",
        },
        {
          id: "father_name_latin",
          type: "text",
          order: 170,
          label: {
            en: "13. Father: full name (Latin)",
            ru: "13. Отец: ФИО (латинскими)",
          },
          placeholder: { en: "IVANOV IVAN", ru: "IVANOV IVAN" },
          layout: "half",
          script: "latin",
        },
        {
          id: "mother_name_latin",
          type: "text",
          order: 180,
          label: {
            en: "14. Mother: full name (Latin)",
            ru: "14. Мать: ФИО (латинскими)",
          },
          placeholder: { en: "IVANOVA MARIA", ru: "IVANOVA MARIA" },
          layout: "half",
          script: "latin",
        },
      ],
    },
    {
      id: "croatia",
      order: 20,
      title: {
        en: "Questions about Croatia (Cyrillic)",
        ru: "Вопросы по Хорватии (заполнять кириллицей)",
      },
      questions: [
        {
          id: "why_croatia",
          type: "textarea",
          order: 10,
          label: {
            en: "1. Why did you choose Croatia for your stay?",
            ru: "1. Почему вы выбрали именно Хорватию для своего пребывания?",
          },
          placeholder: {
            en: "Describe your reasons...",
            ru: "Опишите ваши причины...",
          },
          required: true,
        },
        {
          id: "how_learned_program",
          type: "text",
          order: 20,
          label: {
            en: "2. How did you learn about the Croatia digital nomad residence program?",
            ru: "2. Как вы узнали о программе проживания для цифровых кочевников в Хорватии?",
          },
          placeholder: {
            en: "Source of information...",
            ru: "Источник информации...",
          },
          required: true,
        },
        {
          id: "had_croatia_trp",
          type: "yes_no",
          order: 30,
          label: {
            en: "3. Have you ever previously had a temporary residence permit approved in the Republic of Croatia?",
            ru: "3. Был ли у вас когда-либо ранее одобрен временный вид на жительство в Республике Хорватия?",
          },
          required: true,
        },
        {
          id: "had_other_country_trp",
          type: "yes_no",
          order: 40,
          label: {
            en: "4. Have you previously had a temporary residence permit approved in any other country?",
            ru: "4. Были ли у вас ранее одобрен временный вид на жительство в какой-то другой стране?",
          },
          required: true,
        },
        {
          id: "work_experience",
          type: "textarea",
          order: 50,
          label: {
            en: "5. What do you do and where do you currently work? Briefly describe your work and previous experience.",
            ru: "5. Чем именно вы занимаетесь и где в данный момент работаете? Кратко опишите свою работу и опыт на предыдущих местах.",
          },
          placeholder: {
            en: "Your experience and current activity...",
            ru: "Ваш опыт и текущая деятельность...",
          },
          required: true,
        },
        {
          id: "visited_croatia_before",
          type: "yes_no",
          order: 60,
          label: {
            en: "6. Have you been to Croatia before?",
            ru: "6. Бывали ли вы в Хорватии раньше?",
          },
          required: true,
        },
        {
          id: "travel_history",
          type: "textarea",
          order: 70,
          label: {
            en: "7. In which countries have you been and in what period (month, year)?",
            ru: "7. В каких странах вы были и в какой период (месяц, год)?",
          },
          placeholder: {
            en: "Country, month/year...",
            ru: "Страна, месяц/год...",
          },
        },
      ],
    },
    {
      id: "documents",
      order: 30,
      title: { en: "Documents", ru: "Документы" },
      description: {
        en: "Please attach the required documents",
        ru: "Пожалуйста, прикрепите необходимые документы",
      },
      questions: [
        {
          id: "doc_passport_pdf",
          type: "file",
          order: 10,
          label: {
            en: "International passport (PDF only)",
            ru: "Загранпаспорт (только PDF)",
          },
          required: true,
          accept: ".pdf,application/pdf",
          maxSizeMb: 10,
        },
        {
          id: "has_criminal_record_certificate",
          type: "yes_no",
          order: 20,
          label: {
            en: "Do you have a certificate of no criminal record?",
            ru: "У вас есть справка о несудимости?",
          },
          required: true,
        },
        {
          id: "doc_criminal_record_pdf",
          type: "file",
          order: 30,
          label: {
            en: "Certificate of no criminal record (PDF only)",
            ru: "Справка о несудимости (только PDF)",
          },
          required: true,
          accept: ".pdf,application/pdf",
          maxSizeMb: 10,
          visibleWhen: {
            questionId: "has_criminal_record_certificate",
            equals: "yes",
          },
        },
        {
          id: "doc_other_country_trp_pdf",
          type: "file",
          order: 40,
          label: {
            en: "Residence permit of another country (PDF only)",
            ru: "ВНЖ другой страны (только PDF)",
          },
          accept: ".pdf,application/pdf",
          maxSizeMb: 10,
        },
        {
          id: "has_bank_statement",
          type: "yes_no",
          order: 50,
          label: {
            en: "Do you have a bank statement?",
            ru: "У вас есть банковская выписка?",
          },
          required: true,
        },
        {
          id: "doc_bank_statement_pdf",
          type: "file",
          order: 60,
          label: {
            en: "Bank statement (PDF only)",
            ru: "Банковская выписка (только PDF)",
          },
          required: true,
          accept: ".pdf,application/pdf",
          maxSizeMb: 10,
          visibleWhen: { questionId: "has_bank_statement", equals: "yes" },
        },
        {
          id: "has_contract",
          type: "yes_no",
          order: 70,
          label: {
            en: "Do you have a contract?",
            ru: "У вас есть контракт?",
          },
          required: true,
        },
        {
          id: "doc_contract_pdf",
          type: "file",
          order: 80,
          label: {
            en: "Contract (PDF only)",
            ru: "Контракт (только PDF)",
          },
          required: true,
          accept: ".pdf,application/pdf",
          maxSizeMb: 10,
          visibleWhen: { questionId: "has_contract", equals: "yes" },
        },
        {
          id: "doc_signature_sample",
          type: "file",
          order: 90,
          label: {
            en: "Signature sample",
            ru: "Образец подписи",
          },
          required: true,
          accept: ".jpeg,.jpg,.png,.webp,image/jpeg,image/png,image/webp",
          maxSizeMb: 10,
        },
      ],
    },
    {
      id: "consent",
      order: 40,
      title: { en: "Consent", ru: "Согласие" },
      questions: [
        {
          id: "consent_personal_data",
          type: "boolean",
          order: 10,
          label: {
            en: "I have read the Privacy Policy and consent to the processing of personal data.",
            ru: "Я ознакомился(ась) с Политикой конфиденциальности и даю согласие на обработку персональных данных.",
          },
          required: true,
          linkHref: "/client/privacy",
          linkLabel: {
            en: "Privacy Policy",
            ru: "Политикой конфиденциальности",
          },
        },
      ],
    },
  ],
};
